# Auto-discovered Substack URLs for testing
# Generated by tools/discover_substack_urls.py
#
# Import in test_real_urls.py with:
#   from discovered_test_urls import DISCOVERED_TEST_CASES
#
# Each test case can be a tuple (for basic tests) or a dict (with metadata validation):
# Tuple format: (url, expected_type, description)
# Dict format: {
#   'url': 'https://...',
#   'expected_type': 'note'/'chat'/None,
#   'description': '...',
#   'expected_metadata': {  # Optional, for validation
#       'title': 'Expected Title',  # Can include '...' if Substack adds it
#       'author': 'Expected Author',
#       'should_not_add_ellipsis': True,  # Verify we don't add extra ...
#   }
# }

DISCOVERED_TEST_CASES = [
    {
        "url": "https://www.readmargins.com/p/the-soc2-kabuki-theater",
        "expected_type": None,
        "description": "Discovered regular post",
        "expected_metadata": {
            "title": "Paying the SOC2 Screenshot Tax",
            "author": "Can Duruk",
        },
    },
    {
        "url": "https://www.readmargins.com/p/the-boring-ai-questions-that-actually",
        "expected_type": None,
        "description": "Discovered regular post",
        "expected_metadata": {
            "title": "The Boring AI Questions That Actually Matter",
            "author": "Can Duruk",
        },
    },
    {
        "url": "https://astralcodexten.substack.com/p/mistakes",
        "expected_type": None,
        "description": "Discovered regular post",
        "expected_metadata": {
            "title": "Mistakes",
            "author": "Astral Codex Ten",
        },
    },
    {
        "url": "https://www.astralcodexten.com/p/best-of-moltbook",
        "expected_type": None,
        "description": "Discovered regular post",
        "expected_metadata": {
            "title": "Best Of Moltbook",
            "author": "Scott Alexander",
        },
    },
    {
        "url": "https://www.honest-broker.com/p/my-warning-about-ai-music-from-1988",
        "expected_type": None,
        "description": "Discovered regular post",
        "expected_metadata": {
            "title": "My Warning About AI Music from 1988",
            "author": "Ted Gioia",
        },
    },
    {
        "url": "https://www.honest-broker.com/p/25-ways-to-destroy-a-community",
        "expected_type": None,
        "description": "Discovered regular post",
        "expected_metadata": {
            "title": "25 Ways to Destroy a Community",
            "author": "Ted Gioia",
        },
    },
    {
        "url": "https://substack.com/@contraptions/note/c-191022428",
        "expected_type": "note",
        "description": "Discovered note",
        "expected_metadata": {
            "title": "Leibnizian aesthetics: All is for the most beautiful in this most beautiful of all worlds",
            "author": "Venkatesh Rao",
            "should_not_add_ellipsis": True,   
        }
    },
    {
        "url": "https://substack.com/@uncertaintymindset/note/c-190184676",
        "expected_type": "note",
        "description": "Discovered note",
        "expected_metadata": {
            "title": "Those who manage to break the vicious cycle of avoiding discomfort and becoming less able to deal with discomfort eventually realize that productive discomfort is tolerable and can lead to great and unexpected things.",
            "author": "Vaughn Tan",
            "should_not_add_ellipsis": True,
        }
    },
    {
        "url": "https://substack.com/chat/9973/post/64cc3fbb-ef7b-44a8-b8a9-9e336cc7e71b?target_reply_id=398e3ff6-cc3e-4f8b-a8f6-b7de1f51fc66&showTarget=true&targetReplyId=398e3ff6-cc3e-4f8b-a8f6-b7de1f51fc66",
        "expected_type": "chat",
        "description": "Discovered chat",
        "expected_metadata": {
            "title": "Ok I'm convinced the divergence machine is alive and operational",
            "author": "PAtwater", 
            "should_not_add_ellipsis": True,
        }
    },
]

